// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace PublisherData.CompiledModels
{
    public partial class PubContextModel
    {
        partial void Initialize()
        {
            var author = AuthorEntityType.Create(this);
            var book = BookEntityType.Create(this);

            BookEntityType.CreateForeignKey1(book, author);

            AuthorEntityType.CreateAnnotations(author);
            BookEntityType.CreateAnnotations(book);

            AddAnnotation("ProductVersion", "6.0.10");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
