// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace PublisherData.CompiledModels
{
    [DbContext(typeof(PubContext))]
    public partial class PubContextModel : RuntimeModel
    {
        static PubContextModel()
        {
            var model = new PubContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static PubContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
